// <auto-generated />
using System;
using Mailie.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mailie.Migrations
{
    [DbContext(typeof(MailieDbContext))]
    [Migration("20181009113012_CreateInital")]
    partial class CreateInital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Mailie.DataAccessLayer.MailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<Guid>("Guid");

                    b.Property<string>("Host");

                    b.Property<DateTime>("LastModifiedDateTime");

                    b.Property<string>("Password");

                    b.Property<int>("Port");

                    b.Property<int>("SecureSocketOptions");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("MailAccount");
                });

            modelBuilder.Entity("Mailie.DataAccessLayer.MailAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime>("LastModifiedDateTime");

                    b.Property<int>("MailContactId");

                    b.HasKey("Id");

                    b.HasIndex("MailContactId");

                    b.ToTable("MailAddress");
                });

            modelBuilder.Entity("Mailie.DataAccessLayer.MailContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime>("LastModifiedDateTime");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MailContact");
                });

            modelBuilder.Entity("Mailie.DataAccessLayer.MailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bcc");

                    b.Property<string>("BodyText");

                    b.Property<string>("Cc");

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<DateTime>("Date");

                    b.Property<string>("From");

                    b.Property<Guid>("Guid");

                    b.Property<string>("HtmlBody");

                    b.Property<string>("InReplyTo");

                    b.Property<DateTime>("LastModifiedDateTime");

                    b.Property<int?>("MailContactId");

                    b.Property<string>("MessageId");

                    b.Property<int>("MessageImportance");

                    b.Property<int>("MessagePriority");

                    b.Property<string>("MimeVersion");

                    b.Property<string>("ReplyTo");

                    b.Property<string>("ResentBcc");

                    b.Property<string>("ResentCc");

                    b.Property<DateTime>("ResentDate");

                    b.Property<string>("ResentFrom");

                    b.Property<string>("ResentMessageId");

                    b.Property<string>("ResentReplyTo");

                    b.Property<string>("ResentSender");

                    b.Property<string>("ResentTo");

                    b.Property<string>("Sender");

                    b.Property<string>("Subject");

                    b.Property<string>("TextBody");

                    b.Property<string>("To");

                    b.Property<int>("XPriority");

                    b.HasKey("Id");

                    b.HasIndex("MailContactId");

                    b.ToTable("MailMessage");
                });

            modelBuilder.Entity("Mailie.DataAccessLayer.MailAddress", b =>
                {
                    b.HasOne("Mailie.DataAccessLayer.MailContact", "MailContact")
                        .WithMany("MailAddresses")
                        .HasForeignKey("MailContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mailie.DataAccessLayer.MailMessage", b =>
                {
                    b.HasOne("Mailie.DataAccessLayer.MailContact", "MailContact")
                        .WithMany()
                        .HasForeignKey("MailContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
