// <auto-generated />
using System;
using Mailie.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mailie.Migrations
{
    [DbContext(typeof(MailieDbContext))]
    partial class MailieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Mailie.DataAccessLayer.MailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("Host");

                    b.Property<DateTime>("LastModifiedDateTime");

                    b.Property<int>("Port");

                    b.Property<int>("SecureSocketOptions");

                    b.HasKey("Id");

                    b.ToTable("MailAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
